import { defineField, defineType } from "sanity";

export const order = defineType({
  name: "order",
  title: "Pedido",
  type: "document",
  groups: [
    { name: "info", title: "Información" },
    { name: "customer", title: "Cliente" },
    { name: "items", title: "Productos" },
    { name: "log", title: "Bitácora" },
  ],
  fields: [
    defineField({
      name: "orderNumber",
      title: "# Pedido",
      type: "string",
      group: "info",
      readOnly: true,
    }),
    defineField({
      name: "confirmationToken",
      title: "Token de confirmación",
      type: "string",
      group: "info",
      readOnly: true,
      hidden: true,
      description: "Interno — protege la página pública de confirmación para que no baste con adivinar el número de pedido.",
    }),
    defineField({
      name: "status",
      title: "Estado",
      type: "string",
      group: "info",
      options: {
        list: [
          { title: "⏳ Pendiente", value: "pending" },
          { title: "🏦 Esperando Pago (Transferencia)", value: "awaiting_payment" },
          { title: "✅ Confirmado", value: "confirmed" },
          { title: "📦 En preparación", value: "processing" },
          { title: "🚚 Enviado", value: "shipped" },
          { title: "🏠 Entregado", value: "delivered" },
          { title: "❌ Cancelado", value: "cancelled" },
          { title: "🗑️ Eliminado", value: "deleted" },
        ],
        layout: "radio",
      },
      initialValue: "pending",
    }),
    defineField({ name: "createdAt", title: "Fecha del pedido", type: "datetime", group: "info", readOnly: true }),
    defineField({ name: "notes", title: "Notas internas", type: "text", rows: 3, group: "info" }),
    defineField({
      name: "deliveryMethod",
      title: "Método de entrega",
      type: "string",
      group: "info",
      readOnly: true,
      description: "Elegido por el cliente en el checkout — no editable.",
      options: {
        list: [
          { title: "🚚 Envío a domicilio", value: "shipping" },
          { title: "🏪 Recoger en sucursal", value: "pickup" },
        ],
        layout: "radio",
      },
      initialValue: "shipping",
    }),
    defineField({
      name: "pickupBranch",
      title: "Sucursal de recolección",
      type: "reference",
      to: [{ type: "branch" }],
      group: "info",
      readOnly: true,
      hidden: ({ parent }) => parent?.deliveryMethod !== "pickup",
      description: "Elegida por el cliente en el checkout — no editable. Aparece cuando el método de entrega es 'Recoger en sucursal'.",
    }),
    defineField({
      name: 'shippingInfo',
      title: 'Información de Envío',
      type: 'object',
      group: 'info',
      hidden: ({ parent }) => parent?.deliveryMethod !== 'shipping',
      fields: [
        { name: 'provider', title: 'Paquetería', type: 'string', description: 'Ej: Estafeta, FedEx, DHL' },
        { name: 'trackingNumber', title: 'Número de Guía', type: 'string' },
        { name: 'trackingUrl', title: 'URL de Rastreo (opcional)', type: 'url' },
      ],
    }),
    defineField({
      name: "customer",
      title: "Datos del cliente",
      type: "object",
      group: "customer",
      fields: [
        { name: "name",    title: "Nombre",  type: "string" },
        { name: "company", title: "Empresa", type: "string" },
        { name: "email",   title: "Email",   type: "string" },
        { name: "phone", title: "Teléfono / WhatsApp", type: "string" },
        { name: "address", title: "Dirección (envío o facturación)", type: "text", rows: 3 },
        { name: "colonia", title: "Colonia", type: "string" },
        { name: "city", title: "Ciudad", type: "string" },
        { name: "state", title: "Estado / Provincia", type: "string" },
        { name: "zip", title: "Código postal", type: "string" },
      ],
    }),
    defineField({
      name: "items",
      title: "Productos del pedido",
      type: "array",
      group: "items",
      of: [
        {
          type: "object",
          fields: [
            {
              name: "product",
              title: "Producto",
              type: "reference",
              to: [{ type: "catalogItem" }],
              weak: true,
            },
            { name: "quantity", title: "Cantidad", type: "number", initialValue: 1 },
            { name: "unitPrice", title: "Precio unitario", type: "number" },
            { name: "variantLabel", title: "Variante (opcional)", type: "string" },
          ],
          preview: {
            select: {
              title: "product.title",
              qty: "quantity",
              price: "unitPrice",
            },
            prepare: ({ title, qty, price }) => ({
              title: title ?? "Producto",
              subtitle: `${qty ?? 1} × $${price ?? 0}`,
            }),
          },
        },
      ],
    }),
    defineField({ name: "subtotal", title: "Subtotal", type: "number", group: "items", readOnly: true }),
    defineField({ name: "shipping", title: "Envío", type: "number", group: "items", initialValue: 0 }),
    defineField({ name: "iva", title: "IVA", type: "number", group: "items", readOnly: true, initialValue: 0 }),
    defineField({ name: "total", title: "Total (ya con cashback aplicado)", type: "number", group: "items", readOnly: true }),
    defineField({ name: "cashbackApplied", title: "Cashback usado como pago", type: "number", group: "items", readOnly: true, initialValue: 0 }),
    defineField({ name: "couponCode", title: "Código de cupón usado", type: "string", group: "items", readOnly: true }),
    defineField({ name: "couponDiscount", title: "Descuento de cupón", type: "number", group: "items", readOnly: true, initialValue: 0 }),
    defineField({
      name: "paymentMethod",
      title: "Método de pago",
      type: "string",
      group: "info",
      readOnly: true,
      description: "Elegido por el cliente en el checkout — no editable.",
      options: {
        list: [
          { title: "Mercado Pago", value: "mercadopago" },
          { title: "Transferencia", value: "transfer" },
          { title: "Efectivo", value: "cash" },
          { title: "Tarjeta", value: "card" },
          { title: "WhatsApp / Manual", value: "whatsapp" },
        ],
      },
    }),
    defineField({
      name: "mpPaymentId",
      title: "ID de pago (Mercado Pago)",
      type: "string",
      group: "info",
      readOnly: true,
      description: "ID del pago en Mercado Pago, guardado automáticamente cuando el webhook confirma el pago.",
    }),
    defineField({
      name: "notificationsSent",
      title: "Correos enviados",
      type: "array",
      group: "log",
      readOnly: true,
      description: "Bitácora automática — registra cada correo que se le mandó al cliente sobre este pedido.",
      of: [
        {
          type: "object",
          fields: [
            { name: "type", title: "Tipo", type: "string" },
            { name: "to", title: "Destinatario", type: "string" },
            { name: "sentAt", title: "Enviado", type: "datetime" },
          ],
          preview: {
            select: { type: "type", to: "to", sentAt: "sentAt" },
            prepare: ({ type, to, sentAt }) => ({
              title: type ?? "Correo",
              subtitle: `${to ?? "?"} · ${sentAt ? new Date(sentAt).toLocaleString("es-MX") : ""}`,
            }),
          },
        },
      ],
    }),
  ],
  preview: {
    select: {
      orderNumber: "orderNumber",
      name: "customer.name",
      status: "status",
      total: "total",
    },
    prepare: ({ orderNumber, name, status, total }) => ({
      title: `#${orderNumber ?? "---"} — ${name ?? "Sin nombre"}`,
      subtitle: `${status ?? "pending"} · $${total ?? 0}`,
    }),
  },
  orderings: [
    {
      title: "Más recientes",
      name: "createdAtDesc",
      by: [{ field: "createdAt", direction: "desc" }],
    },
  ],
});
